version: 1
disable_existing_loggers: false
formatters:
  json:
    format: '{"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    level: INFO
    filename: logs/app.log
    maxBytes: 1048576
    backupCount: 3
root:
  level: INFO
  handlers: [console, file]
